# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- script: |
           curl -O https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe
           
           hyperexecute.exe -u neerajn -k J3zIzXZfnxcFZDjaG5SmRb9cIUjoRtjzcX5fPsQcWxVkxBX3Lf -i hyperexecuteStatic.yaml --verbose
